version: '2'
services:
  rabbitmq:
      image: rabbitmq:3-management
      restart: always
      ports:
        - "15672:15672"
        - "5671:5671"
        - "5672:5672"
        - "15671:15671"
        - "25672:25672"
      container_name: rabbitmq
      logging:
            options:
              max-size: "10m"
              max-file: "10"
  registry:
    image: diandian/base-registry
    ports:
      - "8761:8761"
    container_name: base-registry
    logging:
          options:
            max-size: "10m"
            max-file: "10"
  config:
    image: diandian/base-config
    ports:
      - "8888:8888"
    container_name: base-config
    logging:
          options:
            max-size: "10m"
            max-file: "10"
  monitor:
    image: diandian/base-monitor
    ports:
      - "8040:8040"
    container_name: base-monitor
    logging:
          options:
            max-size: "10m"
            max-file: "10"
  zipkin:
    image: diandian/base-zipkin
    ports:
      - "9411:9411"
    container_name: base-zipkin
    logging:
          options:
            max-size: "10m"
            max-file: "10"
  gateway:
    image: diandian/base-gateway
    ports:
      - "8060:8060"
    container_name: base-gateway
    logging:
          options:
            max-size: "10m"
            max-file: "10"
  service-auth:
    image: diandian/service-auth
    ports:
      - "5001:5000"
    container_name: service-auth
    logging:
          options:
            max-size: "10m"
            max-file: "10"
  service-auth2:
      image: diandian/service-auth
      ports:
        - "5002:5000"
      container_name: service-auth2
      logging:
            options:
              max-size: "10m"
              max-file: "10"
  service-auth3:
        image: diandian/service-auth
#        ports:
#          - "5002:5000"
        container_name: service-auth3
        logging:
              options:
                max-size: "10m"
                max-file: "10"